// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
 import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
 import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17g4jAI6H4w--eT0Uif2QmqlVzmucACI',
    appId: '1:692648490438:web:7dc621f7940a306eb02ec7',
    messagingSenderId: '692648490438',
    projectId: 'agro-a60a0',
    authDomain: 'agro-a60a0.firebaseapp.com',
    storageBucket: 'agro-a60a0.firebasestorage.app',
    measurementId: 'G-402T26L2EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPz9-4iaiWM88diff6uXAe93t8D4U0NTA',
    appId: '1:692648490438:android:cdb39c99e0ee51a4b02ec7',
    messagingSenderId: '692648490438',
    projectId: 'agro-a60a0',
    storageBucket: 'agro-a60a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0R3ncZlfGg3GO-eKY3WUnMVptHTjepHU',
    appId: '1:692648490438:ios:6908890d825df704b02ec7',
    messagingSenderId: '692648490438',
    projectId: 'agro-a60a0',
    storageBucket: 'agro-a60a0.firebasestorage.app',
    iosBundleId: 'com.agroconnect.agroconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0R3ncZlfGg3GO-eKY3WUnMVptHTjepHU',
    appId: '1:692648490438:ios:6908890d825df704b02ec7',
    messagingSenderId: '692648490438',
    projectId: 'agro-a60a0',
    storageBucket: 'agro-a60a0.firebasestorage.app',
    iosBundleId: 'com.agroconnect.agroconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC17g4jAI6H4w--eT0Uif2QmqlVzmucACI',
    appId: '1:692648490438:web:a2512a23bebbc65db02ec7',
    messagingSenderId: '692648490438',
    projectId: 'agro-a60a0',
    authDomain: 'agro-a60a0.firebaseapp.com',
    storageBucket: 'agro-a60a0.firebasestorage.app',
    measurementId: 'G-XEJ7HRMPSS',
  );
}
